### ISSUE TITLE
该环境是在linux下的吗？

### ISSUE THREAD

**Issue by huyansheng3** [CraryPrimitiveMan/code-examples#1]
windows不支持新建.babelrc的文件哦

**Comment by harrysun-code** [comment]
@huyansheng3 这边的代码基本都只在linux和mac上测试过，没有用windows测试过

**Comment by harrysun-code** [comment]
@huyansheng3 以.开头的文件可以通过DOS命令来创建

**Comment by huyansheng3** [comment]
@CraryPrimitiveMan  感谢，此方法可行，ES6转ES5成功。
